services:
  - type: web
    name: scrollsnap-backend
    runtime: bun
    repo: https://github.com/johnnyrockets3005/scrollsnap-backend
    branch: main
    buildCommand: bun install
    startCommand: bun run start
    rootDir: src
    plan: free
    region: oregon
