services:
  - type: web
    name: scrollsnap-backend
    runtime: node
    repo: https://github.com/johnnyrockets3005/scrollsnap-backend
    branch: main
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun install --no-cache
    startCommand: |
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"
      bun run start
    rootDir: src
    healthCheckPath: /api/healthz
    plan: free
    region: oregon
