services:
  - type: web
    name: scrollsnap-backend
    env: node
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    healthCheckPath: /api/health
