services:
  - type: web
    name: scrollsnap-backend
    runtime: node # Use node because Render does not yet support 'bun' as runtime
    repo: https://github.com/johnnyrockets3005/scrollsnap-backend
    branch: main
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
      bun install
    startCommand: |
      export PATH="$HOME/.bun/bin:$PATH"
      bun run start
    rootDir: src
    healthCheckPath: /api/healthz
    plan: free
    region: oregon
